version: "3.9"

services:
  coordenador:
    build: ./servico-coordenador
    container_name: coordenador
    ports:
      - "3000:3000"
    networks:
      - sctec-net

  agendamento:
    build: ./servico-agendamento
    container_name: agendamento
    ports:
      - "5000:5000"
    environment:
      - COORDENADOR_URL=http://coordenador:3000
    depends_on:
      - coordenador
    networks:
      - sctec-net

networks:
  sctec-net:
    driver: bridge
